; Generated by AutoGUI 2.1.7a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Menu Tray, Icon, shell32.dll, 201

Gui Add, Button, gconfigurar x358 y325 w80 h23, Configurar
Gui Add, Tab3, x15 y9 w445 h208, Variable Paths|Programs to install
Gui Tab, 1
Gui Add, Text, x28 y43 w100 h26 +0x200, Rabapath
Gui Add, Edit, hWndrabapath veditrabapath x140 y45 w200 h21
Gui Add, Button, gbotonrabapth x354 y45 w80 h23, Edit
Gui Add, Text, x28 y80 w100 h26 +0x200, Documentos
Gui Add, Edit, veditdocumentos x143 y79 w200 h21
Gui Add, Button, gbotondocumentos x353 y77 w80 h23, Edit
Gui Tab, 2
Gui Add, CheckBox, x35 y46 w120 h23, Vim
Gui Add, CheckBox, x35 y78 w120 h23, Chocolate
Gui Add, CheckBox, x35 y112 w120 h23, AutoHotKey
Gui Add, CheckBox, x35 y144 w120 h23, Python

Gui Show, w481 h381, Window
Return

GuiEscape:
GuiClose:
    ExitApp

; Do not edit above this line

botonrabapth:
 {
   FileSelectFolder, rabapath
   GuiControl,, editrabapath, %rabapath% 
   return
 }
  botondocumentos:
 {
   FileSelectFolder, documentos
   GuiControl,, editdocumentos, %documentos% 
   return
 }
configurar:
 {   
    RunWait *RunAs rabainstall.bat %A_ScriptDir% %documentos% ,, Hide
    return
 }
