; Do not edit above this line
;VariablePaths

rabapath = %A_ScriptDir%
EnvGet, documentos, USERPROFILE
documentos=%documentos%.\Documents
EnvGet, archivosDePrograma, ProgramFiles
EnvGet, archivosDePrograma86, ProgramFiles}

; Generated by AutoGUI 2.1.7a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%
Gui Add, Tab3, x15 y9 w445 h208, Variable Paths|Programs to install
Gui Add, Edit, hWndrabapath veditrabapath x140 y45 w200 h21, 
Gui Add, Button, gbotonrabapth x354 y45 w80 h23, Edit
Gui Add, Text, x28 y80 w100 h26 +0x200, Documentos
Gui Add, Edit, veditdocumentos x143 y79 w200 h21,
Gui Add, Button, x303 y79 w80 h23 gbotonrabapth, Editar
Gui Add, Button, x303 y111 w80 h23 gbotondocumentos, Editar
Gui Add, GroupBox, x106 y166 w46 h0, GroupBox
Gui Tab, 2
Gui Add, CheckBox, x35 y46 w120 h23, Vim
Gui Add, CheckBox, x35 y78 w120 h23, Chocolate
Gui Add, CheckBox, x35 y112 w120 h23, AutoHotKey
Gui Add, CheckBox, x35 y144 w120 h23, Python

Gui Show, w493 h396, Window
Return

GuiEscape:
GuiClose:
    ExitApp

botonrabapth:
 {
   FileSelectFolder, rabapath
   GuiControl,, editrabapath, %rabapath% 
   return
 }
 botondocumentos:
 {
   MsgBox % RunWaitOne("rabainstall.bat " A_ScriptDir)
   FileSelectFolder, documentos
   GuiControl,, editdocumentos, %documentos% 
   return
 }
 RunWaitOne(command) {
    ; WshShell object: http://msdn.microsoft.com/en-us/library/aew9yb99
    shell := ComObjCreate("WScript.Shell")
    ; Execute a single command via cmd.exe
    exec := shell.Exec(ComSpec " /C " command)
    ; Read and return the command's output
    return exec.StdOut.ReadAll()
}